version: 2.1
 
orbs:
  android: circleci/android@0.2.1
 
jobs:
  build:
    executor: android/android
    steps:
      - checkout
      - run:
          name: Check java
          command: |
            # set -xe
            # JAVA_VERSION=zulu11.31.11-ca-jdk11.0.3-linux_x64
            # wget https://cdn.azul.com/zulu/bin/${JAVA_VERSION}.tar.gz \
            #   -O /tmp/${JAVA_VERSION}.tar.gz
            # sudo tar -zxf /tmp/${JAVA_VERSION}.tar.gz -C /usr/lib/jvm
            # ls -l /usr/lib/jvm/
            # export JAVA_HOME="/usr/lib/jvm/${JAVA_VERSION}"
            # export PATH=/usr/lib/jvm/${JAVA_VERSION}/bin:$PATH
            
            java -version
      - restore_cache:
          key: android-orb-v1-
      - run:
          name: Chmod permissions
          command: sudo chmod +x ./gradlew
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          key: 'android-orb-v1-{{ epoch }}'
          paths:
            - ~/.android/build-cache
            - ~/.android/cache
      - run:
          name: Run Build
          command: ./gradlew build
      - store_artifacts: 
          path: app/build/reports
          destination: reports
      - run:
          name: Run Tests
          command: ./gradlew lint test
      - store_test_results:
          path: app/build/test-results
      - store_artifacts:  
          path: app/build/outputs/apk/debug/
          destination: artifact-file
